### PR TITLE
Portal looks

### PR DESCRIPTION
**Pull request by QR4SH3D**
https://i.imgur.com/6YSStQT.png
As you can see the one which is highlited is when it's (11, 11) the other one is (12, 12) here you can obviously see it's not even

### CODE REVIEW

**Review by ODAKAB — COMMENTED** [review]
Pull requests are for offering changes, you can offer fixed size like you explained.
Instead just showing the line with a comment.

**Comment by QR4SH3D** [comment]
> 
> 
> Pull requests are for offering changes, you can offer fixed size like you explained.
> Instead just showing the line with a comment.

Oh alright, thanks for the advice ;)

**Comment by Pablete1234** [comment]
I'm unsure as to what the actual pull request is here. Are you just suggesting to increase portal size from 11px to 12px? Any particular reason to do so?

**Comment by ODAKAB** [comment]
image
Can reproduce the issue, my bot draws 12x12 portals with as current setting and even number makes it asymmetric.

**Pull request merged**
