### PR TITLE
Initial commit of JButtonField

### PR DESCRIPTION
**Pull request by pajtor**

### CODE REVIEW

**Comment by Pablete1234** [comment]
How exactly is this editor useful in any way?

**Comment by pajtor** [comment]
¯\_(ツ)_/¯ because I need buttons to perform an action in config, but I will use the beforeConfig method then

**Comment by Pablete1234** [comment]
> ¯_(ツ)_/¯ because I need buttons to perform an action in config, but I will use the beforeConfig method then

The behavior on this button cannot be edited as it is right now, which is why i'm asking how is this useful

**Comment by pajtor** [comment]
Will try doing this later in PluginAPI instead

**Pull request closed without merging**
