### PR TITLE
Fix table updating in config & prevent memory leak on change

### PR DESCRIPTION
**Pull request by Punikekk**

### CODE REVIEW

**Comment by Pablete1234** [comment]
I believe this to be missing patches, at the very least [`75903a7` (#157)](https://github.com/darkbot-reloaded/DarkBot/pull/157/commits/75903a7c7543e5cc155bf24d34e9c88ba4b3ba74) is missing

**Comment by Punikekk** [comment]
need to inculde this https://github.com/darkbot-reloaded/DarkBot/pull/157/commits/3e9c9f3ef420aece2abead68a140e61e27612cb9

**Comment by Pablete1234** [comment]
then include it too

**Comment by Punikekk** [comment]
pushed

**Review by Pablete1234 — APPROVED** [review]

**Pull request merged**
